ci: always test integration without recording

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -120,7 +120,7 @@ jobs:
       id: set-script
       run: |
         if [ "${{ github.ref }}" == "refs/heads/main" ] || ( [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.base_ref }}" == "main" ] ); then
-          echo "integration-test-script=bash -c \"set -o pipefail && rps install --release && rps test record 2>&1 | grep -v -E '(UNSUPPORTED: curExtension->sType|VkDevice|VkInstance)'\"" >> $GITHUB_ENV
+          echo "integration-test-script=bash -c \"set -o pipefail && rps install --release && rps test integration 2>&1 | grep -v -E '(UNSUPPORTED: curExtension->sType|VkDevice|VkInstance)'\"" >> $GITHUB_ENV
         else
           echo "integration-test-script=bash -c \"set -o pipefail && rps install --debug && rps test integration 2>&1 | grep -v -E '(UNSUPPORTED: curExtension->sType|VkDevice|VkInstance)'\"" >> $GITHUB_ENV
         fi
